version: "3"
  
services:
  app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
    command: /bin/sh -c "cd /app && yarn dev"
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    # M1Mac用
    platform: linux/amd64