import type { NextPage } from 'next';
import Link from 'next/link';
import Layout from '../components/layout';
import GeneralButton from '../components/generalButton';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title className="">第二外国語アプリ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css"
          rel="stylesheet"
        />
      </Head>
      <Layout title="第二外国語アプリ">
        <div className="">
          <div>
            <p className="text-orange-800 text-5xl">Bonjour le monde!!</p>
            <p className="text-orange-800 text-xl">
              人称や格を楽しく学べるアプリ
            </p>
          </div>
          <img src="../../top.png" />
        </div>
        <div className="">
          <div className="">
            <Link href="/register">問題を解く</Link>
            <br />
            <Link href="/question">問題を登録する</Link>
            <GeneralButton text="フランス語" />
            <GeneralButton text="ロシア語" />
          </div>
        </div>
      </Layout>
    </>
  );
};

export default Home;
